// Filipino Childhood Games - Complete metadata for seeding
const filipinoGames = [
  {
    name: 'Patintero',
    slug: 'patintero',
    filipinoName: 'Patintero',
    description: 'A thrilling grid-based tag game where runners try to cross lines while guards patrol them. One of the most iconic Filipino street games!',
    history: 'Patintero, also known as "harangang-taga" or "tubigan," is one of the oldest and most popular Filipino outdoor games. It dates back to pre-colonial Philippines and was played on moonlit nights using water-marked lines on the ground. The name comes from the Spanish word "patente" meaning privilege or right of way.',
    rules: '1. Draw a rectangular grid on the ground with horizontal and vertical lines.\n2. One team guards the lines (patrollers), the other team tries to cross all lines without being tagged.\n3. Guards can only move along their assigned lines.\n4. Runners must cross from one end to the other and back.\n5. If a runner is tagged, the teams switch roles.\n6. The team that crosses all members wins.',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Tubigan', description: 'Uses water to mark lines on the ground', region: 'Visayas' },
      { name: 'Harangang-taga', description: 'Night version played under moonlight', region: 'Luzon' },
    ],
    type: '2d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 10,
    category: 'outdoor',
    difficulty: 'medium',
    xpReward: { win: 120, loss: 30, draw: 60 },
    isOfflinePlayable: true,
  },
  {
    name: 'Tumbang Preso',
    slug: 'tumbang-preso',
    filipinoName: 'Tumbang Preso',
    description: 'Knock down the tin can with your slipper while the "It" guards it! A classic Filipino street game of aim and speed.',
    history: 'Tumbang Preso, meaning "fallen prisoner," originated as a street game in the Philippines. It teaches children aim, strategy, and teamwork. The game uses an empty tin can and slippers (tsinelas), making it accessible to all children regardless of economic background.',
    rules: '1. Place an empty can (the "prisoner") inside a circle.\n2. One player is "It" and guards the can.\n3. Other players throw their slippers to knock down the can.\n4. While the can is down, players retrieve their slippers.\n5. "It" must stand the can up before tagging a player without their slipper.\n6. A tagged player becomes the new "It."',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Tumbang Lata', description: 'Uses a larger tin can', region: 'Mindanao' },
    ],
    type: '2d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 8,
    category: 'outdoor',
    difficulty: 'easy',
    xpReward: { win: 100, loss: 25, draw: 50 },
    isOfflinePlayable: true,
  },
  {
    name: 'Luksong Baka',
    slug: 'luksong-baka',
    filipinoName: 'Luksong Baka',
    description: 'Jump over the "cow"! Players take turns leaping over a crouching player who gradually stands taller with each round.',
    history: 'Luksong Baka, meaning "Jump over the Cow," is a traditional Filipino outdoor game similar to leapfrog. It originated from rural Philippines where children would mimic jumping over carabaos (water buffalos) in the rice fields. The game develops agility and physical coordination.',
    rules: '1. One player crouches as the "baka" (cow).\n2. Other players take turns jumping over the "baka."\n3. After each round, the "baka" rises slightly higher.\n4. Players who fail to jump over become the next "baka."\n5. The last player who can still jump wins.',
    origin: 'Rural Philippines',
    variations: [
      { name: 'Luksong Kalabaw', description: 'Jump over a "water buffalo" — higher starting position', region: 'Luzon' },
    ],
    type: '2d',
    modes: ['pvc', 'pvp', 'practice'],
    minPlayers: 2,
    maxPlayers: 10,
    category: 'physical',
    difficulty: 'easy',
    xpReward: { win: 80, loss: 20, draw: 40 },
    isOfflinePlayable: true,
  },
  {
    name: 'Chinese Garter',
    slug: 'chinese-garter',
    filipinoName: 'Chinese Garter',
    description: 'A jumping game using a stretchy garter! Players must jump over the garter as it rises from ankle to head height.',
    history: 'Chinese Garter is a popular Filipino street game especially among girls. Despite its name, it was popularized in the Philippines during the 1970s-90s. It uses a long garter or rubber band chain and develops flexibility, jumping ability, and creativity in movement.',
    rules: '1. Two players hold the garter at both ends, starting at ankle height.\n2. Players must jump over or perform required moves.\n3. Height levels: ankle, knee, hip, waist, chest, shoulder, head, "forever" (arms raised).\n4. Players can use different techniques: single jump, split, or creative moves.\n5. Failing at a level means you become a garter holder.\n6. The player who reaches the highest level wins.',
    origin: 'Philippines (Urban areas)',
    variations: [
      { name: 'Ten-Twenty', description: 'Uses specific counting patterns', region: 'Metro Manila' },
    ],
    type: '2d',
    modes: ['pvc', 'pvp', 'practice'],
    minPlayers: 2,
    maxPlayers: 6,
    category: 'physical',
    difficulty: 'medium',
    xpReward: { win: 100, loss: 25, draw: 50 },
    isOfflinePlayable: true,
  },
  {
    name: 'Sungka',
    slug: 'sungka',
    filipinoName: 'Sungka',
    description: 'An ancient Filipino board game of strategy! Distribute shells across pits to capture the most — a Filipino version of Mancala.',
    history: 'Sungka is one of the oldest known Filipino games, dating back to pre-colonial times. It is a mancala-type game played with a carved wooden board (the sungkaan) with two rows of seven pits and two larger head pits. The game uses shells (sigay), seeds, or pebbles as playing pieces. Archaeological evidence suggests it was played by ancient Filipinos as early as the 10th century.',
    rules: '1. Each player has 7 small pits and 1 head pit (ulo).\n2. Place 7 shells in each small pit (98 shells total).\n3. Players take turns picking up all shells from one of their pits.\n4. Distribute shells one-by-one counter-clockwise, including your head but skipping opponent\'s head.\n5. If the last shell lands in an occupied pit, pick up all shells and continue.\n6. If the last shell lands in your empty pit across from opponent\'s occupied pit, capture both.\n7. If the last shell lands in your head, you get another turn.\n8. Game ends when all pits on one side are empty. The player with the most shells wins.',
    origin: 'Pre-colonial Philippines',
    variations: [
      { name: 'Sungka ng Bata', description: 'Simplified version for younger children with 5 pits', region: 'Nationwide' },
      { name: 'Kunggit', description: 'Variation from the Visayas region', region: 'Visayas' },
    ],
    type: '2d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 2,
    category: 'strategy',
    difficulty: 'medium',
    xpReward: { win: 150, loss: 35, draw: 75 },
    isOfflinePlayable: true,
  },
  {
    name: 'Piko',
    slug: 'piko',
    filipinoName: 'Piko',
    description: 'Filipino hopscotch! Hop through numbered squares while tossing a stone marker. A game of balance and precision.',
    history: 'Piko is the Filipino version of hopscotch, played throughout the Philippines for generations. The name comes from the act of hopping on one foot. Children draw the piko grid on the ground using chalk or charcoal and use flat stones as markers (pamato).',
    rules: '1. Draw a hopscotch grid with numbered squares.\n2. Toss your marker (pamato) into square 1.\n3. Hop through all squares (skip the one with your marker).\n4. Single squares = one foot, double squares = two feet.\n5. On the way back, pick up your marker.\n6. Repeat for each numbered square.\n7. Miss a square or step on a line = lose your turn.\n8. First to complete all squares wins.',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Piko sa Bilog', description: 'Circular version of the game', region: 'Visayas' },
    ],
    type: '2d',
    modes: ['pvc', 'practice'],
    minPlayers: 1,
    maxPlayers: 4,
    category: 'outdoor',
    difficulty: 'easy',
    xpReward: { win: 80, loss: 20, draw: 40 },
    isOfflinePlayable: true,
  },
  {
    name: 'Agawan Base',
    slug: 'agawan-base',
    filipinoName: 'Agawan Base',
    description: 'Capture the enemy base! Two teams race to tag the opposing team\'s base while defending their own.',
    history: 'Agawan Base, meaning "Capture the Base," is a popular Filipino outdoor team game. It teaches teamwork, strategy, and speed. The game is similar to capture the flag but uses bases (trees, posts, or marked areas) instead of flags.',
    rules: '1. Two teams each have a base (a designated area or object).\n2. Players try to tag the opposing team\'s base while defending their own.\n3. Players can be tagged when they leave their base.\n4. Tagged players are "frozen" until a teammate taps them free.\n5. A newer player leaving base can tag an older-left player.\n6. First team to touch the enemy base wins.',
    origin: 'Philippines (Nationwide)',
    variations: [],
    type: '2d',
    modes: ['pvp', 'practice'],
    minPlayers: 4,
    maxPlayers: 12,
    category: 'outdoor',
    difficulty: 'medium',
    xpReward: { win: 120, loss: 30, draw: 60 },
    isOfflinePlayable: true,
  },
  {
    name: 'Langit Lupa',
    slug: 'langit-lupa',
    filipinoName: 'Langit Lupa',
    description: 'Heaven and Earth! The "it" can only tag you when you\'re on the ground (lupa). Get up high to be safe in "langit" (heaven)!',
    history: 'Langit Lupa, meaning "Heaven and Earth," is a beloved Filipino chasing game. Players must stay elevated (langit/heaven) to avoid being tagged by "it" who can only catch players on the ground (lupa/earth). The game has been played in Filipino neighborhoods for generations.',
    rules: '1. One player is "It."\n2. "It" sings: "Langit, lupa, impyerno... im-im-impyerno!"\n3. On "impyerno," all players must be elevated (on chairs, rocks, stairs, etc.).\n4. Players on the ground can be tagged.\n5. Players cannot stay in "langit" for more than 10 seconds.\n6. Tagged player becomes the new "It."',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Langit-Lupa-Impyerno', description: 'Three levels including "hell" (ground)', region: 'Luzon' },
    ],
    type: '2d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 3,
    maxPlayers: 10,
    category: 'outdoor',
    difficulty: 'easy',
    xpReward: { win: 90, loss: 22, draw: 45 },
    isOfflinePlayable: true,
  },
  {
    name: 'Teks',
    slug: 'teks',
    filipinoName: 'Teks',
    description: 'Flip and collect picture cards! Match your opponent\'s card by flipping your own. A game of skill and collecting.',
    history: 'Teks (from "text" cards) is a Filipino card game played with collectible picture cards featuring superheroes, anime characters, and local celebrities. Popular in the 1980s-2000s, children would trade and battle with their card collections. The game teaches strategy and dexterity.',
    rules: '1. Each player places a card face-down on the ground.\n2. Take turns flipping your card by slapping or fanning.\n3. If your card flips on top of the opponent\'s card, you win both cards.\n4. Different techniques: "pitik" (flick), "hampas" (slap), "saplak" (fan).\n5. Player who collects the most cards wins.\n6. Special cards may have bonus values.',
    origin: 'Philippines (Urban areas)',
    variations: [
      { name: 'Spider-Man Teks', description: 'Uses only superhero cards', region: 'Metro Manila' },
    ],
    type: '2d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 4,
    category: 'dexterity',
    difficulty: 'easy',
    xpReward: { win: 80, loss: 20, draw: 40 },
    isOfflinePlayable: true,
  },
  {
    name: 'Sipa',
    slug: 'sipa',
    filipinoName: 'Sipa',
    description: 'Keep the washer-shuttlecock airborne using only your feet! A game of coordination and endurance.',
    history: 'Sipa is the Philippines\' national sport and traditional game. The name means "kick" in Filipino. Players kick a washer topped with colorful plastic strips (sipa) to keep it in the air. It predates badminton and has been played since the 15th century, believed to be introduced through trade with Southeast Asian neighbors.',
    rules: '1. Use only your feet/legs to kick the sipa.\n2. Keep the sipa in the air as long as possible.\n3. Count each successful kick.\n4. If the sipa touches the ground, your turn ends.\n5. Player with the highest count wins.\n6. In team mode, pass the sipa between teammates without dropping.',
    origin: 'Pre-colonial Philippines',
    variations: [
      { name: 'Sipa sa Paa', description: 'Only foot kicks allowed', region: 'Nationwide' },
      { name: 'Sipa sa Tuhod', description: 'Knee kicks included', region: 'Visayas' },
    ],
    type: '2d',
    modes: ['pvc', 'pvp', 'practice'],
    minPlayers: 1,
    maxPlayers: 4,
    category: 'dexterity',
    difficulty: 'medium',
    xpReward: { win: 100, loss: 25, draw: 50 },
    isOfflinePlayable: true,
  },
  {
    name: 'Luksong Tinik',
    slug: 'luksong-tinik',
    filipinoName: 'Luksong Tinik',
    description: 'Jump over the "thorns"! Players must leap over progressively higher stacked hands and feet.',
    history: 'Luksong Tinik, meaning "Jump over Thorns," is a traditional Filipino outdoor game. Two players sit on the ground and stack their hands and feet to create "thorns" that other players must jump over. The game develops agility and jumping ability.',
    rules: '1. Two players sit facing each other and stack their fists/feet.\n2. Other players jump over the "thorns" (stacked hands/feet).\n3. Start with one fist, then add more to increase height.\n4. Players who touch the thorns become the next "thorn" pair.\n5. Continue until only one player can clear the height.',
    origin: 'Philippines (Nationwide)',
    variations: [],
    type: '2d',
    modes: ['pvc', 'practice'],
    minPlayers: 3,
    maxPlayers: 8,
    category: 'physical',
    difficulty: 'easy',
    xpReward: { win: 80, loss: 20, draw: 40 },
    isOfflinePlayable: true,
  },
  {
    name: 'Tagu-taguan',
    slug: 'taguan',
    filipinoName: 'Tagu-taguan',
    description: 'Filipino hide and seek! The "It" counts while everyone hides, then must find all players before they reach base.',
    history: 'Tagu-taguan is the Filipino version of hide and seek. The "It" covers their eyes and counts while singing "Tagu-taguan, maliwanag ang buwan..." (Hide and seek, the moon is bright). It\'s played in every Filipino neighborhood and teaches spatial awareness and stealth.',
    rules: '1. One player is "It" and stands at the base.\n2. "It" closes eyes and counts while singing the taguan song.\n3. Other players hide within the playing area.\n4. "It" tries to find and tag hidden players.\n5. Hidden players can try to reach the base before "It."\n6. Last player found, or first to reach base safely, wins.',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Tagu-taguan sa Dilim', description: 'Night version — played in the dark', region: 'Nationwide' },
    ],
    type: '2d',
    modes: ['pvp', 'practice'],
    minPlayers: 3,
    maxPlayers: 10,
    category: 'outdoor',
    difficulty: 'easy',
    xpReward: { win: 90, loss: 22, draw: 45 },
    isOfflinePlayable: true,
  },
  {
    name: 'Holen',
    slug: 'holen',
    filipinoName: 'Holen / Jolens',
    description: 'Marbles! Flick your marble to hit targets or knock opponents\' marbles out of the ring. A classic 3D game of precision.',
    history: 'Holen, also known as Jolens, is the Filipino marble game. Glass or clay marbles are used. The game was extremely popular in the 1980s-90s. Children would collect and trade rare marbles. The term "holen" comes from the Hokkien word for marbles.',
    rules: '1. Draw a circle on the ground.\n2. Each player places their marbles inside the circle.\n3. Players take turns shooting their "pamato" (shooter marble) to knock marbles out.\n4. Marbles knocked out belong to the shooter.\n5. If your shooter stays in the circle, you lose it.\n6. Player who collects the most marbles wins.',
    origin: 'Philippines (Nationwide)',
    variations: [
      { name: 'Tig-isa', description: 'One-on-one marble shooting', region: 'Luzon' },
      { name: 'Dagatan', description: 'Larger playing area version', region: 'Visayas' },
    ],
    type: '3d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 6,
    category: 'dexterity',
    difficulty: 'medium',
    xpReward: { win: 120, loss: 30, draw: 60 },
    isOfflinePlayable: true,
  },
  {
    name: 'Trumpo',
    slug: 'trumpo',
    filipinoName: 'Trumpo',
    description: 'Spinning top battles! Launch your wooden top and try to knock out your opponents\' tops from the ring.',
    history: 'Trumpo is the Filipino spinning top game, derived from the Spanish word "trompo." Wooden tops with metal tips are wound with string and launched. The game was popular in the 1970s-90s and was a rite of passage for Filipino boys. Skilled players could perform tricks like "sleeper" and "walk the dog."',
    rules: '1. Each player has a wooden top (trumpo) and string.\n2. Wind the string around the top.\n3. Launch the top by throwing and pulling the string.\n4. In battle mode: try to knock opponent\'s top over.\n5. In trick mode: perform spinning tricks.\n6. Longest spinning top wins endurance matches.\n7. Top knocked out of the ring is eliminated.',
    origin: 'Philippines (Spanish influence)',
    variations: [
      { name: 'Trumpong Bakal', description: 'Metal-tipped tops for battle', region: 'Luzon' },
    ],
    type: '3d',
    modes: ['pvp', 'pvc', 'practice'],
    minPlayers: 2,
    maxPlayers: 4,
    category: 'dexterity',
    difficulty: 'hard',
    xpReward: { win: 150, loss: 35, draw: 75 },
    isOfflinePlayable: true,
  },
  {
    name: 'Jackstone',
    slug: 'jackstone',
    filipinoName: 'Jackstone',
    description: 'Pick up jacks while bouncing a ball! A game of speed, coordination, and dexterity popular among Filipino kids.',
    history: 'Jackstone has been a Filipino childhood staple since the American colonial period. The game uses small metal jacks (star-shaped pieces) and a small rubber ball. It was especially popular among girls during recess and after school. The game develops hand-eye coordination and quick reflexes.',
    rules: '1. Scatter 10 jacks on a flat surface.\n2. Toss the ball up, pick up jacks, and catch the ball after one bounce.\n3. Start with "onesies" (pick one at a time), then "twosies," etc.\n4. Must not touch other jacks while picking up.\n5. Ball must bounce exactly once.\n6. Dropping jacks or missing the ball = lose your turn.\n7. First player to complete through "tensies" wins.',
    origin: 'Philippines (American influence)',
    variations: [
      { name: 'Jackstone ni Nanay', description: 'Uses stones instead of metal jacks', region: 'Rural areas' },
    ],
    type: '3d',
    modes: ['pvc', 'pvp', 'practice'],
    minPlayers: 1,
    maxPlayers: 4,
    category: 'dexterity',
    difficulty: 'medium',
    xpReward: { win: 100, loss: 25, draw: 50 },
    isOfflinePlayable: true,
  },
  {
    name: 'Taguan 3D',
    slug: 'taguan-3d',
    filipinoName: 'Tagu-taguan',
    description: 'A 3D hide-and-seek experience! Navigate a virtual Filipino neighborhood to find hidden players or stay hidden.',
    history: 'This is a modern 3D adaptation of the classic Filipino Tagu-taguan, set in a virtual Filipino neighborhood with bahay kubo, sari-sari stores, and basketball courts.',
    rules: '1. Same rules as traditional Taguan but in a 3D environment.\n2. Navigate using keyboard/mouse controls.\n3. "It" has a flashlight to search in dark areas.\n4. Hidden players can peek to check "It"\'s position.\n5. Proximity alerts when "It" is near.\n6. First to reach base safely or last found wins.',
    origin: 'Philippines (Digital adaptation)',
    variations: [],
    type: '3d',
    modes: ['pvp', 'practice'],
    minPlayers: 3,
    maxPlayers: 8,
    category: 'outdoor',
    difficulty: 'medium',
    xpReward: { win: 130, loss: 32, draw: 65 },
    isOfflinePlayable: false,
  },
];

module.exports = { filipinoGames };
